"use client";
import {useState,useEffect,useRef} from 'react';
import {ShieldCheck,Fingerprint,LockKeyhole,FlaskConical,FileJson,Activity,Download,Check,Pause,RotateCcw,Play,ShieldX} from 'lucide-react';
import {Button} from '@/components/ui/button';
async function verifyBundle(bundle:any,trust:any,expected?:string){const m=await import('@/lib/witness/protocol.mjs');return m.verifyBundle(bundle,trust,expected);}
const PINNED_RECORDER='B62qo36XaXAU73vRgghNuNm6wiB4g8grqFRdvJMwpaw7FmXwvLC2opo';
type Event={fields:string[];signature:string;hash:string};
type Run={runId:string;status:string;events:Event[];dispatches:number;checkpoint?:{digest:string}};
type Evidence={proofVerified:boolean;proofTests:number;gatewayTests:number;root:string;count:number;dispatches:number;checkpointDigest:string;chainStatus:string;address?:string;transactionHash?:string;verifiedAt:string};
const scenarios=[['read','Read approved package','A permitted action establishes the baseline.'],['write','Write to the registry','Attempt a side effect outside the mission.'],['egress','Reach an external host','Ask for an unapproved destination.'],['cross-run','Read another run','Attempt to cross the mission boundary.'],['replay','Replay an authorization','Try to use the same operation twice.'],['outage','Interrupt recording','Inject a failure before the record is written.']];
const labels=(e:Event)=>({operation:e.fields[1]==='1'?'package.read':'package.write',scope:({'1':'own registry','2':'external host','3':'other run'} as Record<string,string>)[e.fields[2]],allowed:e.fields[6]==='1',reason:e.fields[4]==='0'?'Replay rejected':e.fields[1]==='2'?'Write not permitted':e.fields[2]!=='1'?'Scope not permitted':e.fields[6]==='0'?'Budget exhausted':'Package returned'});
export default function Home(){
 const [run,setRun]=useState<Run|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('Start a run or execute the full adversarial suite. Only synthetic resources are used.'),[error,setError]=useState(''),[hidden,setHidden]=useState(false),[paused,setPaused]=useState(false),[verification,setVerification]=useState(''),[evidence,setEvidence]=useState<Evidence|null>(null),[chainMessage,setChainMessage]=useState(''),[proofBusy,setProofBusy]=useState(false);
 const lastNonce=useRef<string|null>(null),actions=useRef<Record<string,(x?:string)=>Promise<unknown>>>({});
 useEffect(()=>{void fetch('/api/lab').then(r=>r.json()).then((d:any)=>{if(d.run)setRun(d.run);}).catch(()=>setError('The recorder could not be reached.'));void fetch('/evidence/manifest.json').then(r=>r.ok?r.json():null).then(d=>setEvidence(d as Evidence|null)).catch(()=>{});},[]);
 async function post(body:unknown){const r=await fetch('/api/lab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let d:any;try{d=await r.json();}catch{throw Error('Gateway unavailable. Refresh to reconcile the recorded state.');}if(!r.ok)throw Error(d.error??'Request failed.');if(d.run)setRun(d.run);if(d.message)setMessage(d.message);return d;}
 async function perform(fn:()=>Promise<unknown>){if(busy)throw Error('An operation is already in progress.');setBusy(true);setError('');setHidden(false);try{return await fn();}catch(e){setError(e instanceof Error?e.message:'Operation failed.');}finally{setBusy(false);}}
 async function start(){lastNonce.current=null;setPaused(false);setVerification('');return post({action:'start'});}
 async function scenario(id:string){if(id==='outage'){const d=await post({action:'outage'});setPaused(true);return d;}const nonce=id==='replay'?lastNonce.current:crypto.randomUUID();if(!nonce)throw Error('Read the approved package once before replaying it.');if(id==='read')lastNonce.current=nonce;return post({action:'request',operation:id==='write'?'write':'read',scope:id==='egress'?'external':id==='cross-run'?'other':'own',nonce});}
 async function suite(){await start();for(const id of ['read','write','egress','cross-run','replay','outage','read','read','read'])await scenario(id);setMessage('Suite complete: 3 permitted reads, 5 recorded denials, and 1 injected recorder outage with no dispatch.');return {completed:true};}
 async function seal(){const d=await post({action:'export'});return d.bundle;}
 async function check(tamper=false){const b=await seal();const expected=b.checkpoint.digest;if(tamper)b.events[0].fields[7]=(BigInt(b.events[0].fields[7])+1n).toString();try{const result=await verifyBundle(b,{recorder:PINNED_RECORDER},expected);setVerification(tamper?'Unexpected: altered evidence passed.':`${result.eventCount} signatures verified. Policy, ordering, replay checks, and the sealed checkpoint match.`);return result;}catch(e){if(!tamper)throw e;const reason=e instanceof Error?e.message:'Verification failed';setVerification('Tampering detected: '+reason+' The server’s original record is unchanged.');return {tamperDetected:true,reason};}}
 async function download(){const b=await seal();const url=URL.createObjectURL(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='witness-'+b.runId+'.json';a.click();URL.revokeObjectURL(url);}
 async function restore(){const d:any=await(await fetch('/api/lab')).json();if(!d.run)throw Error('No recorded run is available.');setRun(d.run);setHidden(false);setMessage('The server’s signed record was fetched again. Clearing the client view did not alter it.');return {eventCount:d.run.events.length};}
 async function reference(){setProofBusy(true);try{const [b,t]:any[]=await Promise.all([fetch('/evidence/reference-bundle.json').then(r=>r.json()),fetch('/evidence/trust.json').then(r=>r.json())]);if(t.recorder!==PINNED_RECORDER)throw Error('Reference key changed.');const d=await verifyBundle(b,{recorder:PINNED_RECORDER},evidence?.checkpointDigest);setChainMessage(`Reference signatures verified in this browser: ${d.eventCount} events, ${d.dispatches} dispatches. Use the downloadable verifier for the ZK proof.`);}catch(e){setChainMessage(e instanceof Error?e.message:'Reference verification failed.');}finally{setProofBusy(false);}}
 async function checkChain(){setProofBusy(true);try{const r=await fetch('/api/checkpoint');const d:any=await r.json();setChainMessage(d.message);}catch{setChainMessage('Live chain check unavailable. This does not invalidate the downloaded signature evidence.');}finally{setProofBusy(false);}}
 actions.current={suite:()=>perform(suite),start:()=>perform(start),scenario:(id)=>perform(()=>scenario(id!)),verify:()=>perform(()=>check()),restore:()=>perform(restore)};
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>unknown}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[{name:'run_witness_experiment',description:'Create a synthetic mission and run the complete adversarial suite. Updates the visible event record.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty input object.');return actions.current.suite();}},{name:'verify_witness_record',description:'Seal the current run and verify its signatures and fixed policy in the browser. This prevents further actions in this run.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw Error('Expected an empty input object.');return actions.current.verify();}}];for(const tool of tools){try{void Promise.resolve(context.registerTool({...tool,annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:life.signal})).catch(()=>{});}catch{}}return()=>life.abort();},[]);
 const active=!!run&&run.status==='open',events=hidden?[]:run?.events??[],denied=run?.events.filter(e=>e.fields[6]==='0').length??0;
 return <main>
 <header className="masthead"><a className="wordmark" href="/"><Fingerprint size={25}/>WITNESS<span>AGENT SAFETY LAB</span></a><nav><a href="#experiment">Experiment</a><a href="#evidence">Evidence</a><a href="/readme">Readme</a></nav><span className="edition">POC / 01</span></header>
 <section className="intro"><div><p className="eyebrow">TRUST THE BOUNDARY. VERIFY THE EVIDENCE.</p><h1>Give the agent a task.<br/><span>Keep control of the consequences.</span></h1><p>Test an external permission gate and signed flight recorder. Inspect what happened, what was blocked, and what the evidence can prove.</p></div><div className="scope-note"><FlaskConical size={22}/><strong>A controlled experiment</strong><span>Synthetic tool requests. Real server decisions. Explicit limits.</span></div></section>
 <div className="boundary-strip"><div><span>01</span><strong>Untrusted client</strong><small>Proposes an action</small></div><div><span>02</span><strong>External gateway</strong><small>Checks mission policy</small></div><div><span>03</span><strong>Signed recorder</strong><small>Commits with the effect</small></div><div><span>04</span><strong>Independent evidence</strong><small>Verify outside the agent</small></div></div>
 <section className="lab" id="experiment"><aside className="controls"><div className="section-label"><span>THE EXPERIMENT</span><span>01—06</span></div><h2>Try the boundary.</h2><p>One mission: read your run’s approved package. At most 3 reads, within an 8-event trace.</p><Button className="primary-action" disabled={busy} onClick={()=>perform(suite)}><Play size={15}/>{busy?'Working…':'Run adversarial suite'}</Button><Button className="reset-action" variant="ghost" disabled={busy} onClick={()=>perform(start)}><RotateCcw size={14}/>Start an empty run</Button><div className="scenario-list">{scenarios.map(([id,title,desc],i)=><button key={id} disabled={busy||!active||(id==='replay'&&!lastNonce.current)||(id!=='outage'&&(run?.events.length??0)>=8)} onClick={()=>perform(()=>scenario(id))} className="scenario"><span className="scenario-number">0{i+1}</span><span><strong>{title}</strong><small>{desc}</small></span></button>)}</div></aside>
 <div className="record-panel"><div className="panel-heading"><div><Activity size={18}/><h2>Witnessed events</h2></div><span className="tag">{run?.status==='sealed'?'SEALED RECORD':'SERVER RECORD'}</span></div>
 {run&&<div className="run-stats"><div><strong>{run.dispatches}</strong><span>Package reads</span></div><div><strong>{denied}</strong><span>Denied requests</span></div><div><strong>{paused?'1':'0'}</strong><span>Injected outage</span></div><code title={run.runId}>{run.runId.slice(0,8)}</code></div>}
 {!events.length?<div className="empty-record"><ShieldCheck size={40}/><h3>{hidden?'Client view cleared. Evidence survives.':'The recorder lives outside the client.'}</h3><p>{hidden?'Restore the record to fetch the authoritative signed events again.':'Run the experiment to watch the gateway allow or deny each request.'}</p>{hidden&&<Button variant="secondary" onClick={()=>perform(restore)} disabled={busy}>Restore server record</Button>}</div>:<ol className="event-list">{events.map(e=>{const l=labels(e);return <li key={e.hash}><span className="event-index">{e.fields[0].padStart(2,'0')}</span><span className={l.allowed?'decision allow':'decision deny'}>{l.allowed?<Check size={14}/>:<ShieldX size={14}/>} {l.allowed?'ALLOW':'DENY'}</span><div className="event-content"><strong>{l.operation}<span> / {l.scope}</span></strong><small>{l.reason}</small></div><span className="signed-label" title={e.signature}><LockKeyhole size={12}/>SIGNED</span></li>})}</ol>}
 <div className="result-note" role="status" aria-live="polite">{error?<span className="error-text">{error}</span>:<><span className="result-marker">{paused?<Pause size={15}/>:<Activity size={15}/>}</span>{message}</>}</div>
 <div className="record-footer"><LockKeyhole size={16}/><span>Live runs have server-signed evidence. The separately published reference run has a ZK proof and checkpoint status below.</span></div></div></section>
 <section className="verify-strip"><div><h3>Try to change the story.</h3><p>Sealing closes the run and signs its exact event sequence.</p></div><div className="verify-actions"><Button variant="outline" disabled={busy||!run?.events.length} onClick={()=>perform(()=>check())}>Seal & verify</Button><Button variant="outline" disabled={busy||!run?.events.length} onClick={()=>perform(()=>check(true))}>Tamper with a copy</Button><Button variant="outline" disabled={busy||!run?.events.length} onClick={()=>{setHidden(true);setMessage('Only this browser view was cleared.');}}>Clear client view</Button><Button variant="outline" disabled={busy||!run?.events.length} onClick={()=>perform(download)}><Download size={15}/>Export</Button></div>{verification&&<p className="verification-result" role="status">{verification}</p>}</section>
 <section className="evidence-section" id="evidence"><div><p className="eyebrow">INSPECT, DON’T ASSUME</p><h2>Evidence you can take with you.</h2><p>The fixed reference trace is signed by the same recorder as this demo. Its proof checks the private event sequence, policy decisions, replay protection, and 3-read limit.</p><p className="fine-print">The reference uses disclosed synthetic data so the result is reproducible. Live visitor runs are signed, but are not automatically proved or anchored.</p><div className="download-links"><a href="/evidence/reference-bundle.json" download>Reference trace</a><a href="/evidence/proof.json" download>ZK proof</a><a href="/evidence/verification-key.json" download>Verification key</a><a href="/witness-source.zip" download>Source & verifier</a></div><div className="command-block"><span>VERIFY LOCALLY · NODE 22+</span><code>cd witness-demo<br/>npm ci<br/>cd proof && npm install<br/>npm run verify</code></div></div>
 <div className="evidence-card"><div className="evidence-heading"><FileJson size={23}/><span>REFERENCE RUN</span></div><div className="evidence-line"><span>Gateway tests</span><strong>{evidence?`${evidence.gatewayTests} passed`:'Loading evidence…'}</strong></div><div className="evidence-line"><span>Real proof verification</span><strong>{evidence?.proofVerified?'Passed in release test':'Pending'}</strong></div><div className="evidence-line"><span>Proof checks</span><strong>{evidence?`${evidence.proofTests} passed`:'—'}</strong></div><div className="evidence-line"><span>Zeko checkpoint</span><strong>{evidence?.chainStatus==='included'?'L2 state confirmed':'Awaiting deployment'}</strong></div><div className="evidence-line"><span>Ethereum finality</span><strong className="muted-value">Not asserted</strong></div>{evidence?.root&&<div className="root-value"><span>TRACE COMMITMENT</span><code>{evidence.root}</code></div>}{evidence?.address&&<div className="root-value"><span>CHECKPOINT ACCOUNT</span><code>{evidence.address}</code></div>}<div className="evidence-buttons"><Button variant="outline" disabled={proofBusy||!evidence} onClick={reference}>Verify reference signatures</Button><Button variant="outline" disabled={proofBusy||evidence?.chainStatus!=='included'} onClick={checkChain}>Check live checkpoint</Button></div>{chainMessage&&<p className="chain-message" role="status">{chainMessage}</p>}<a className="test-report-link" href="/evidence/gateway-tests.json">Inspect gateway test report</a></div></section>
 <section className="limits"><h2>What this experiment establishes.</h2><div><p><strong>Evidence and enforcement.</strong> A browser cannot authorize an out-of-policy service effect or edit the server’s signed trace through this API. A verifier can reject altered evidence.</p><p><strong>A defined trust boundary.</strong> The gateway, signing key, database, verifier, and deployment operator remain trusted. The POC uses a synthetic service and an injected outage, not a hostile model or OS escape.</p><p><strong>A foundation for containment.</strong> Real deployments also need isolation, mediated service credentials, egress control, independent retention, and reliable shutdown. An air gap exports evidence offline.</p></div><a href="/readme">Read the questions and answers</a></section>
 <footer><span>WITNESS / EXPERIMENTAL</span><p>Eight-event proof of concept. Signature validity, policy-proof validity, L2 inclusion, and settlement finality are separate claims.</p></footer></main>;
}
