import {Fingerprint} from 'lucide-react';
const qa=[
 ['Can capable agents be constrained before alignment is solved?','For a defined boundary, permissions can be enforced without trusting the planner. Here, the server permits only reads from this run’s registry, up to three successful reads. Writes, other scopes, and replays are rejected. This is a bounded demonstration, not universal containment.'],
 ['Can the agent rewrite the logs?','The client cannot sign or edit the authoritative record through the API. Signed events bind the run, policy, order, and previous event; a terminal signature seals the exact trace. The verifier rejects changed or truncated evidence against an expected checkpoint. The recorder, operator, and database remain trusted.'],
 ['What happens when monitoring fails?','An injected recorder failure prevents any new record or service effect. The synthetic service counter and signed event commit atomically. This is not a killed-host or workload-shutdown test. External services require durable authorization, idempotency, result recording, and crash reconciliation.'],
 ['Why zero-knowledge proofs and a blockchain?','The real reference proof checks the signed batch, policy, ordering, replay checks, and read budget while keeping event fields private to the proof. The included contract can optionally publish that commitment on Zeko Sepolia. This release needs no live contract address or settlement. The synthetic trace is also disclosed for reproduction. Visitor runs are signed but not automatically proved or anchored.'],
 ['Does this stop SSRF or create an air gap?','No. An external-destination request is denied without making a network request. The demo does not test a vulnerable proxy, DNS rebinding, kernel exploitation, or physical isolation. Production systems need independent egress control and hardened infrastructure. An actual air gap exports reviewed evidence offline.'],
 ['What is the honest claim?','A working gateway can constrain synthetic actions and preserve evidence outside an untrusted client. Signatures and real policy proofs can be verified independently. Completeness of capture, trustworthy enforcement, key custody, retention, and finality remain separate requirements.']
];
export default function Readme(){return <main><header className="masthead"><a className="wordmark" href="/"><Fingerprint size={25}/>WITNESS<span>AGENT SAFETY LAB</span></a><nav><a href="/">Experiment</a><a href="/README.md" download>Download README</a></nav></header><article className="readme"><p className="eyebrow">THE QUESTIONS THAT MATTER</p><h1>What does the proof<br/>of concept actually prove?</h1><p className="readme-lead">A short account of the guarantees, the experiment, and the work still required for real containment.</p>{qa.map(([q,a])=><section key={q}><h2>{q}</h2><p>{a}</p></section>)}<a className="readme-back" href="/">Run the experiment</a></article><footer><span>WITNESS / EXPERIMENTAL</span><p>Read the full README and source for reproduction commands and the precise trust model.</p></footer></main>;}
